### ISSUE TITLE
Mac MPT does not start

### ISSUE THREAD

**Issue by priddy** [EHRI/rspub-gui#1]
MPT version 0.0.0
MacOS 10.11.6
MetadataPublishingTool.app will not open on double click of the icon.

**Comment by dans-er** [comment]
This happens when you install the tool in a directory where you, as a normal user, have no write permission. Logging now is done in the install directory and the application quits immediately because it cannot create the logging file.

Will be fixed in next release.

Solution for now:
Install the tool in a directory where you have write permission.

**Comment by dans-er** [comment]
MPT is now logging to (subdirectory of) user home. See also: [Log file location](http://rspub-gui.readthedocs.io/en/latest/rst/rsgui.miscellaneous.html#log-file-location)
